spring:
  application:
    name: project-management
  flyway:
    clean-disabled: true
  datasource:
    url: jdbc:mysql://node0.com:3306/db_pm?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000

mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker_str
  type-aliases-package: com.pm.infrastructure.dataobject

server:
  port: 10660
  servlet:
    context-path: /pm
  tomcat:
    connection-timeout: 10s
