spring:
  application:
    name: project-management
  datasource:
    url: jdbc:mysql://node0.com:3306/db_pm?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
server:
  port: 10660
  servlet:
    context-path: /pm
  tomcat:
    connection-timeout: 10s
