spring:
  profiles:
    active: prod
  application:
    name: project-management
  jackson:
    default-property-inclusion: non_null
  flyway:
    clean-disabled: true

mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker_str
  type-enums-package: com.pm.infrastructure.dataobject.enums

server:
  port: 10660
  servlet:
    context-path: /pm
    encoding:
      charset: UTF-8
  tomcat:
    connection-timeout: 10s
